version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: docker-example-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
      - auth
    networks:
      - docker-example-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: docker-example-frontend
    command: yarn dev
    restart: unless-stopped
    networks:
      - docker-example-network

  api:
    build: ./api
    command: yarn dev
    restart: unless-stopped
    container_name: docker-example-api
    environment:
      - DB_HOST=api_db
      - DB_NAME=test_db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_PORT=3306
      - PORT=3001
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db
    networks:
      - docker-example-network

  auth:
    build: ./auth
    container_name: docker-example-auth
    command: yarn dev
    restart: unless-stopped
    environment:
      - DB_NAME=auth_db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_PORT=3306
      - DB_HOST=auth_db
      - PORT=3002
      - API_URL=http://api:3001
    depends_on:
      - auth_db
    networks:
      - docker-example-network

  api_db:
    image: mysql:latest
    container_name: docker-example-api-db
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - docker-example-network

  auth_db:
    image: mysql:latest
    container_name: docker-example-auth-db
    restart: always
    environment:
      MYSQL_DATABASE: 'auth_db'
      # MYSQL_USER: 'user_auth'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - db-auth:/var/lib/mysql
    networks:
      - docker-example-network

volumes:
  db-data:
  db-auth:

networks:
  docker-example-network:
    driver: bridge
