import Head from 'next/head';
import axios from 'axios';
import styles from '../styles/Home.module.css';

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>1</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{data}</div>
    </div>
  );
}

// export async function getServerSideProps() {
//   let { data } = await axios.get('/api/test');
//   return {
//     props: { data }, // will be passed to the page component as props
//   };
// }
